import {
  Home,
  Settings,
  ShoppingCart,
  BarChart3,
  Users,
  Box,
  Warehouse,
  Receipt,
  Wrench,
  Cpu,
  CreditCard,
  Pill,
  Shirt,
  Utensils,
  Bed,
  Scissors,
  Gamepad,
  Dumbbell,
  Stethoscope,
  GraduationCap,
  Layers,
  Tag,
  Truck,
  FileText,
  Calendar,
  LayoutGrid,
  KanbanSquare,
  Clock,
  Sparkles,
  Plus,
  Search,
  Edit,
  Trash2,
  X,
  Check,
  AlertTriangle,
  LogOut,
  Filter,
  ChevronDown,
  Star,
  RefreshCw,
  Database,
  Gauge,
  Pause,
  Play,
  Sun,
  Moon,
  ChevronUp,
  Download,
  Upload,
  Save,
  RotateCw,
  type LucideIcon,
} from 'lucide-react'

const MAP: Record<string, LucideIcon> = {
  home: Home,
  settings: Settings,
  cart: ShoppingCart,
  chart: BarChart3,
  users: Users,
  box: Box,
  warehouse: Warehouse,
  receipt: Receipt,
  wrench: Wrench,
  cpu: Cpu,
  'credit-card': CreditCard,
  pill: Pill,
  shirt: Shirt,
  utensils: Utensils,
  bed: Bed,
  scissors: Scissors,
  gamepad: Gamepad,
  dumbbell: Dumbbell,
  stethoscope: Stethoscope,
  'graduation-cap': GraduationCap,
  layers: Layers,
  tag: Tag,
  truck: Truck,
  file: FileText,
  calendar: Calendar,
  layout: LayoutGrid,
  kanban: KanbanSquare,
  clock: Clock,
  sparkles: Sparkles,
  plus: Plus,
  search: Search,
  edit: Edit,
  trash: Trash2,
  x: X,
  check: Check,
  alert: AlertTriangle,
  logout: LogOut,
  filter: Filter,
  'chevron-down': ChevronDown,
  star: Star,
  refresh: RefreshCw,
  database: Database,
  gauge: Gauge,
  pause: Pause,
  play: Play,
  sun: Sun,
  moon: Moon,
  up: ChevronUp,
  down: ChevronDown,
  download: Download,
  upload: Upload,
  save: Save,
  rotate: RotateCw,
}

export function Icon({ name, className = 'h-5 w-5' }: { name: string; className?: string }) {
  const Cmp = MAP[name] || Box
  return <Cmp className={className} />
}
